version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/qbthonui
permissions:
  - object: /home/ubuntu/qbthonui/
    pattern: "**"
    owner: ubuntu
    group: ubuntu
hooks:
  AfterInstall:
    - location: /start.sh
      timeout: 900
      runas: ubuntu