version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
      docker: 18
  pre_build:
    commands:
    - echo "Qbthon UI pre-build phase
    - $(aws ecr get-login --no-include-email --region $AWS_DEFAULT_REGION)
    - TAG="$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 8)"
  build:
    commands:
    - echo "Qbthon UI build phase"
    - docker build --tag "895164885144.dkr.ecr.us-east-2.amazonaws.com/qbthonspartanui:${TAG}" .
  post_build:
    commands:
    - echo "Qbthon UI post-build phase"
    - docker push "895164885144.dkr.ecr.us-east-2.amazonaws.com/qbthonspartanui:${TAG}"
    - cp ./qbthonui-deployment.yml qbthonui-deployment_temp.yml  
    - sed -i s/TAG_ID/$TAG/g qbthonui-deployment_temp.yml
artifacts:
  files:
   - '**/*'